### PR TITLE
Add French family checker

### PR DESCRIPTION
**Pull request by maggick**
Yet another one (I may have group them in just one branch)

### CODE REVIEW

**Comment by maggick** [comment]
Nevertheless I do not see the interest of having EN_military_checker and EN_road_checker, the words in the first one are not all related to the army (like boat or pilot).

**Comment by digininja** [comment]
I didn't create the military or road checker, just accepted what was submitted.

**Comment by maggick** [comment]
Yeah I have seen the author comment at the beginning of the file.

**Comment by maggick** [comment]
thanks for quick reaction for all the merges ;)

**Comment by WebBreacher** [comment]
I created those to more-easily parse results from password cracks. We can definitely classify/organize them better. Let's create an issue(s) for these things and address.

**Pull request merged**
