### PR TITLE
Adding new checkers

### PR DESCRIPTION
**Pull request by WebBreacher**
Added several new checkers that search for specific terms of a given category. Some are fun to see (such as in the emotion_checker...does your password list have more "love" or more "hate" passwords?). Some can show disgruntled employees (emotion_checker, military_checker). Others (family_checker, road_checker, vehicle_checker) are just interesting.

1 - emotion
2 - explicit
3 - family
4 - military
5 - reiligon
6 - road
7 - sport
8 - vehicle

### CODE REVIEW

**Comment by digininja** [comment]
What is the correct way for me to check this out so I can test it?

I would normally just do a clone from your repo but sure there is a better
way

**Comment by WebBreacher** [comment]
I'm no git-expert here but ya, that is what I've done in the past is git clone the submitter's repo.

**Comment by WebBreacher** [comment]
@digininja I added to the original checkers and made a US_State checker too.

**Comment by digininja** [comment]
Not ignoring these, just got 2 reports to finish before Christmas so
pushing on them first.

**Pull request merged**
