### PR TITLE
Adds US Keyboard layout

### PR DESCRIPTION
**Pull request by dginther**
Keyboard layout for US keyboards

### CODE REVIEW

**Comment by digininja** [comment]
What is the point in this file, what is it to be used for?

**Comment by dginther** [comment]
Did you not request assistance with creating keyboard layouts for other than uk, mbp, and keypad?

**Comment by dginther** [comment]
from: https://digi.ninja/projects/passpat.php#moreLayouts
We Need More Layouts

The more keyboard layouts Passpat has the better it will work, please submit more. The ones I'd like to see are:

US
Dvorak
Australian
Any non-western keyboard, Thai, Japanese etc.

**Comment by digininja** [comment]
You've got the wrong project, this is Pipal not Pass to Pat. You want to be looking in here:

https://github.com/digininja/pat_to_pass/blob/master/pat_to_pass.rb

**Comment by dginther** [comment]
ok

**Pull request closed without merging**
